{
 "title": "Neo4j Dashboard",
 "description": "Neo4j cluster monitoring dashboard, with Prometheus data source.\nRead more at https://graphaware.com/neo4j/2019/06/11/monitoring-neo4j-prometheus.html",
 "tags": [ "neo4j" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "env", "label": "Env:", "query": { "query": "label_values(namespace)" } },
   {
    "name": "job",
    "query": {
     "query": "label_values({namespace=~\"$env\"}, job)"
    }
   },
   {
    "name": "neo4j_instance",
    "label": "Neo4j instance",
    "query": {
     "query": "label_values({job=~\"neo4j.*\", namespace=~\"$env\"}, pod)"
    }
   },
   {
    "name": "leader",
    "query": {
     "query": "query_result(neo4j_causal_clustering_core_is_leader == 1)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{env=~\"$env\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "$neo4j_instance Status",
   "type": "stat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "neo4j_instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='$job', namespace=~'$env', pod=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Counters of Graph Items",
   "type": "timeseries",
   "description": "Total number of graph items: node, relationships, ...",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)_ids_in_use(.*)\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_ids_in_use(.+)\")",
     "legendFormat": "{{pod}}: {{label}} "
    }
   ]
  },
  {
   "title": "Graph Items Creation Rate (ids)",
   "type": "timeseries",
   "description": "Per-second Average Rate of Increase of Data Counters",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(neo4j_ids_in_use_property{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "Property rate {{instance}}"
    },
    {
     "expr": "rate(\n  label_replace({__name__=~\"neo4j_(.*)_ids_in_use_(.*)\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_ids_in_use(.+)\")[$interval:]\n  )",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Node creation speed (ids)",
   "type": "gauge",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(\n    sum(label_replace({__name__=~\"neo4j_(.*)_ids_in_use_node\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_ids_in_use(.+)\"))[$interval:]\n)",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Relationship creation speed (ids)",
   "type": "gauge",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(\n    sum(label_replace({__name__=~\"neo4j_(.*)_ids_in_use_relationship\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_ids_in_use(.+)\"))[$interval:]\n)"
    }
   ]
  },
  {
   "title": "Property creation speed (ids)",
   "type": "gauge",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(\n    sum(label_replace({__name__=~\"neo4j_(.*)_ids_in_use_property\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_ids_in_use(.+)\"))[$interval:]\n)"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Last Closed Transaction ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(\n    sum(label_replace({__name__=~\"neo4j_(.*)transaction_last_closed_tx_id_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)transaction_last_closed_tx_id_total(.+)\"))[$interval:]\n)"
    }
   ]
  },
  {
   "title": "Committed Transaction Speed",
   "type": "gauge",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(\n    sum(label_replace({__name__=~\"neo4j_(.*)_transaction_committed_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_transaction_committed_total(.+)\"))[$interval:]\n)"
    }
   ]
  },
  {
   "title": "Rolled back Transaction Speed",
   "type": "gauge",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(\n    sum(label_replace({__name__=~\"neo4j_(.*)_transaction_rollbacks_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_itransaction_rollbacks_total(.+)\"))[$interval:]\n)"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "All transaction metrics",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)transaction_(started|committed|rollbacks|terminated)_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)_transaction_(.+)\")",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Committed transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)_transaction_committed_(.*)\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_transaction_committed_(.+)\")",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Last Committed Write Transaction ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "neo4j_transaction_last_committed_tx_id_total{job='$job', instance=\"$leader\"}",
     "legendFormat": "Last Committed Transaction ID"
    },
    {
     "expr": "irate(\n    sum(label_replace({__name__=~\"neo4j_(.*)_transaction_last_committed_tx_id_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_transaction_last_committed_tx_id_total(.+)\"))[$interval:]\n)"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "description": "Active Transactions - Read and Write - \nand Peak concurrent",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)_transaction_active_(.*)\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_transaction_active_(.+)\")",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Committed Read Transaction Rate",
   "type": "timeseries",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(\nlabel_replace({__name__=~\"neo4j_(.*)_transaction_committed_read_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_transaction_committed_(.+)\")[$interval:]\n)",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Committed Write Transaction Rate",
   "type": "timeseries",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(\nlabel_replace({__name__=~\"neo4j_(.*)_transaction_committed_write_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_transaction_committed_(.+)\")[$interval:]\n)",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Committed Transaction Rate",
   "type": "timeseries",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(\nlabel_replace({__name__=~\"neo4j_(.*)_transaction_committed_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_transaction_committed_(.+)\")[$interval:]\n)",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Database entity sizes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)_ids_in_use(.*)\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_ids_in_use(.+)\")",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  { "title": "Database metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  { "title": "Bolt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Bolt Messages (received vs started)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_dbms_bolt_messages_(received|started)_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_dbms_bolt_messages_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Messages Queue",
   "type": "graph",
   "description": "Messages received - Messages started",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_bolt_messages_received_total{job='$job', pod=~\"$neo4j_instance\"} - neo4j_dbms_bolt_messages_started_total{job='$job', pod=~\"$neo4j_instance\"}",
     "legendFormat": "Bolt Msg Queue Length {{pod}}"
    },
    {
     "expr": "rate(neo4j_dbms_bolt_messages_received_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "Bolt msg received rate {{instance}}"
    },
    {
     "expr": "rate(neo4j_dbms_bolt_messages_started_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "Bolt msg started rate {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Rate of message queue time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dbms_bolt_accumulated_queue_time_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_dbms_bolt_connections_.+\", job=\"$job\", pod=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_dbms_bolt_connections_(.+)\")",
     "legendFormat": "{{pod}}: {{label}} "
    }
   ]
  },
  {
   "title": "Bolt Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_dbms_bolt_sessions.+\",  job=\"$job\", pod=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_dbms_bolt_sessions_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt rate of message processing time",
   "type": "graph",
   "description": "Processing and Queuing time per bolt message",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dbms_bolt_accumulated_processing_time_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Page Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Page cache faults",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_page_faults_total{job=\"$job\", pod=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache faults/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dbms_page_cache_page_faults_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache Pins and Unpins rate (pins/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dbms_page_cache_pins_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "pins {{instance}}"
    },
    {
     "expr": "rate(neo4j_dbms_page_cache_unpins_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "unpins {{instance}}"
    }
   ]
  },
  {
   "title": "Page cache evictions rate (evictions/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dbms_page_cache_evictions_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "evictions{{instance}}"
    },
    {
     "expr": "rate(neo4j_dbms_page_cache_eviction_exceptions_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "eviction exceptions {{instance}}"
    }
   ]
  },
  {
   "title": "Page cache evictions",
   "type": "graph",
   "description": "Eviction process in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_evictions_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache flushes",
   "type": "graph",
   "description": "The total number of flushes executed by the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_flushes_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits",
   "type": "graph",
   "description": "The total number of page hits happened in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_hits_total{job='$job', pod='$neo4j_instance'}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits Rate (hits/sec)",
   "type": "graph",
   "description": "Per-second Neo4j Page Cache Hits",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dbms_page_cache_hits_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page cache flushes rate (flushes/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_dbms_page_cache_flushes_total{job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Page Cache Hit Ratio",
   "type": "graph",
   "description": "The ratio of hits to the total number of lookups in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_dbms_page_cache_hit_ratio{job=\"$job\", pod=~\"$neo4j_instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Neo4j Log Rotation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_log_.+\", job=\"$job\", pod=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "description": "Neo4j Checkpoints. \nCheckpointing is the process of flushing all pending page updates from the page cache to the store files",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)check_point_(events|total_time)_total\", job=\"$job\", pod=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)\")",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Checkpoint event duration sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)_check_point_duration\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)_check_point_duration\")",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "VM Garbage Collector",
   "type": "graph",
   "description": "Time and counters",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+_vm_gc_time_g1_.+_generation_total\", job=\"$job\", pod=~\"$neo4j_instance\"}",
     "legendFormat": "{{__name__}} {{pod}}"
    },
    {
     "expr": "delta({__name__=~\".+_vm_gc_time_g1_old_generation_total\", job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "delta g1 old g total {{pod}}"
    },
    {
     "expr": "delta({__name__=~\".+_vm_gc_time_g1_young_generation_total\", job=\"$job\", pod=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "delta g1 young g total {{pod}}"
    }
   ]
  },
  {
   "title": "VM Live Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_vm_thread_count{job=\"$job\", pod=~\"$neo4j_instance\"}",
     "legendFormat": "vm live threads {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap Size",
   "type": "graph",
   "description": "Heap memory (eden space, old generation, survivor space)\nNon-heap memory (metaspace, compressed class space, code cache)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".+_vm_memory_pool_g1_(eden|old|survivor).*\", job=\"$job\", pod=~\"$neo4j_instance\"}) by (pod)",
     "legendFormat": "{{pod}} heap"
    },
    {
     "expr": "sum({__name__=~\".+_vm_memory_pool_(code|compressed|metaspace).*\", job=\"$job\", pod=~\"$neo4j_instance\"}) by (pod)",
     "legendFormat": "{{pod}} non-heap"
    }
   ]
  },
  {
   "title": "JVM Used Buffer rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"neo4j_.+vm_memory_buffer_direct_used\", job=\"$job\", pod=~\"$neo4j_instance\"}",
     "legendFormat": "memory buffer direct used {{pod}}"
    },
    {
     "expr": "{__name__=~\"neo4j_vm_memory_buffer_mapped_used\", job=\"$job\", pod=~\"$neo4j_instance\"}",
     "legendFormat": "memory buffer mapped used{{pod}}"
    }
   ]
  },
  { "title": "Causal Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Committed read transaction rate - Leader Vs Others",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_read_total{job=\"$job\", instance=\"$leader\"}[$interval])",
     "legendFormat": "Leader {{instance}}"
    },
    {
     "expr": "sum(rate(neo4j_transaction_committed_read_total{job=\"$job\", instance!=\"$leader\"}[$interval]))",
     "legendFormat": "Others sum"
    }
   ]
  },
  {
   "title": "Committed write transaction rate - Leader Vs Others",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_write_total{job=\"$job\", instance=\"$leader\"}[$interval])",
     "legendFormat": "Leader {{instance}}"
    },
    {
     "expr": "sum(rate(neo4j_transaction_committed_write_total{job=\"$job\", instance!=\"$leader\"}[$interval]))",
     "legendFormat": "Others sum"
    }
   ]
  },
  {
   "title": "Replicate pulls rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_causal_clustering_read_replica_pull_updates_total[$interval])"
    }
   ]
  },
  {
   "title": "Core message processing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "neo4j_causal_clustering_core_message_processing_timer{job=\"$job\", pod=~\"$neo4j_instance\"} * 10000",
     "legendFormat": "{{quantile}} {{instance}}"
    }
   ]
  },
  {
   "title": "Core election timeout ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_causal_clustering_core_message_processing_timer_election_timeout{job=\"$job\", instance=~\"$neo4j_instance\", quantile=\"0.5\"} * 10000",
     "legendFormat": "median {{instance}}"
    },
    {
     "expr": "neo4j_causal_clustering_core_message_processing_timer_election_timeout_count{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "count {{instance}}"
    }
   ]
  },
  { "title": "Cypher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Cyper replan events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)_cypher_replan_events_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_cypher_replan_events_total(.*)\")",
     "legendFormat": "{{pod}}: {{label}}"
    }
   ]
  },
  {
   "title": "Cyper wait time",
   "type": "graph",
   "description": "The total number of seconds waited between query replans",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 155 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_(.*)_cypher_replan_wait_time_total\", job='$job', pod=~\"$neo4j_instance\"}, \"label\", \"$1.$2\", \"__name__\", \"neo4j_(.*)_cypher_replan_wait_time_total(.+)\")"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 } }
 ]
}