version: '3.7'

services:
  grafana:
   image: grafana/grafana:6.7.1
   volumes:
     - grafana_data:/var/lib/grafana
   #  - ./grafana/provisioning:/etc/grafana/provisioning #will be set up later
   restart: unless-stopped
   networks:
     - traefik_network
   labels:
     - "traefik.docker.network=traefik_network"
     - "traefik.enable=true"
     - "traefik.http.routers.grafana-secure.entrypoints=https"
     - "traefik.http.routers.grafana-secure.rule=Host(`grafana.${TRAEFIK_HOST}`)"

  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - traefik_network
    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus-secure.entrypoints=https"
      - "traefik.http.routers.prometheus-secure.rule=Host(`prometheus.${TRAEFIK_HOST}`)"
    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  traefik_network:
    external: true
