version: '3.7'

services:
   grafana:
    image: grafana/grafana:6.7.1
    volumes:
      - grafana_data:/var/lib/grafana
    #  - ./grafana/provisioning:/etc/grafana/provisioning #will be set up later
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.${TRAEFIK_HOST}`)"
      - "traefik.http.routers.grafana-secure.tls=true"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  traefik_network:
    external: true
