{
 "title": "Traefik",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env:",
    "query": "label_values(node_uname_info{job=~\"nodeexporter\"}, env)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{env=~\"$env\"}, nodename)"
   },
   { "name": "entrypoint", "query": "label_values(entrypoint)" }
  ]
 },
 "panels": [
  { "title": "$node stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$node status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_config_reloads_failure_total{nodename=~\"$node\"}) / sum(traefik_config_reloads_total{nodename=~\"$node\"} * 100)"
    }
   ]
  },
  {
   "title": "$node return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{nodename=~\"$node\"}) by (code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "$node response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{nodename=~\"$node\"}) / sum(traefik_service_requests_total{nodename=~\"$node\"}) * 1000"
    }
   ]
  },
  {
   "title": "Total requests over 5min $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{nodename=~\"$node\"}[5m]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (entrypoint, method, code) (rate(traefik_entrypoint_requests_total{nodename=~\"$node\",entrypoint=~\"$entrypoint\",code=\"200\"}[5m]))",
     "legendFormat": "{{ entrypoint }}.{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Other status codes over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (entrypoint, method, code) (rate(traefik_entrypoint_requests_total{nodename=~\"$node\",entrypoint=~\"$entrypoint\",code!=\"200\"}[5m]))",
     "legendFormat": "{{ entrypoint }}.{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests by node",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{nodename=~\"$node\"}) by (nodename) ",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total{nodename=~\"$node\",entrypoint =~ \"$entrypoint\"}) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  { "title": "services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Service rates over 5min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{nodename=~\"$node\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Bad Status codes over 5min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{nodename=~\"$node\", code>\"399\"}[5m])) by (service, code)",
     "legendFormat": "{{service}}: {{code}}"
    }
   ]
  }
 ]
}